apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-ebizapp-deployment
  namespace: client02
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-ebizapp
  template:
    metadata:
      labels:
        app: frontend-ebizapp
    spec:
      containers:
      - name: frontend-ebizapp
        image: sushantjadhav/ebizapp:v1.0.0
        resources:
          limits:
            memory: 200Mi
            cpu: 100m
        ports:
          - containerPort: 3000            
        volumeMounts:
          - name: frontend-config-volume
            mountPath: /etc/frontend/conf.d
      volumes:
        - name: frontend-config-volume
          configMap:
            name: frontend-config       
       
            

