apiVersion: v1
kind: Service
metadata:
  name: backend-ebizapp-service  
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: backend-ebizapp   
