apiVersion: v1
kind: Pod
metadata:
  name: envfrom-secret2
  namespace: client02
spec:
  containers:
  - name: postgres-container
    image: postgres:9.6.23
    resources:
          limits:
            memory: 512Mi
            cpu: 10m
            
    envFrom:
    - secretRef:
        name: test-secret
        