apiVersion: v1
kind: Pod
metadata:
  name: envfrom-secret1
  namespace: client02
spec:
  containers:
  - name: ebizapp-redis
    image: sushantjadhav/ebizapp-redis:latest
    resources:
          limits:
            memory: 512Mi
            cpu: 10m
    
    envFrom:
    - secretRef:
        name: test-secret
        