apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: client02
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:9.6.23
          env:
            - name: PRODUCTION
              value: "True"
            - name: POSTGRES_USER 
              value: postgres
            - name: POSTGRES_PASSWORD
              value: Rushi0321
         
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: postgres-pv-claim1
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-pv-claim1
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi