apiVersion: v1
kind: ConfigMap
metadata:
   name: postgres-config
   namespace: client02
...
  volumeMounts:
    - name: postgres-pv-claim1
      mountPath: /var/lib/postgresql/data
    - name: postgres-config
      mountPath: /etc/postgresql
...
  volumeClaimTemplates:
    - metadata:
        name: postgres-pv-claim1
      spec:
...
  volumes:
    - name: postgres-config 
      configMap:
        name: postgres-config