apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: client02
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-container
  template:
    metadata:
      labels:
        app: postgres-container
    spec:
      containers:
        - name: postgres-container
          image: postgres:9.6.23
          ports:
            - containerPort: 5432
          resources:
           limits:
            memory: 100Mi
            cpu: 10m
          env:
            - name: PRODUCTION
              value: "True"
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: Rushi0321           
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: ros_gql_db
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres-pv-claim1