apiVersion: v1
kind: Pod
metadata:
  name: secret-test2-pod
spec:
  containers:
    - name: backend-ebizapp
      image: sushantjadhav/ebizapi:latest
      resources:
          limits:
            memory: 512Mi
            cpu: 10m
      volumeMounts:
        # name must match the volume name below
        - name: secret-volume2
          mountPath: /etc/secret-volume2
          readOnly: true
  # The secret data is exposed to Containers in the Pod through a Volume.
  volumes:
    - name: secret-volume2
      secret:
        secretName: test-secret